[book]
authors = ["Carl Fredrik Samson"]
language = "en"
multilingual = false
src = "src"
title = "The Node Experiment - Exploring Async Basics with Rust"

[output.html]
git-repository-url = "https://github.com/cfsamson/book-exploring-async-basics"
google-analytics = "UA-149686420-1"
